pipeline:
  projectIdentifier: datarobotusermodels
  orgIdentifier: Custom_Models
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: datarobot-user-models
        build: <+input>
  stages:
    - parallel:
        - stage:
            name: test_unit
            identifier: test_unit
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: run unit tests
                      identifier: run_unit_tests
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: python:<+matrix.python_version>
                        shell: Bash
                        command: ./harness_scripts/base_check/unit_tests_entrypoint.sh
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - results.tests.xml
                      strategy:
                        matrix:
                          python_version:
                            - "3.9"
                            - "3.10"
                            - "3.11"
                            - "3.12"
                            - "3.13"
                            - "3.14"
                          nodeName: <+matrix.python_version>
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
        - stage:
            name: test_integration
            identifier: test_integration
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: test_integration
                      identifier: test_integration
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: datarobot/drum-builder
                        shell: Bash
                        command: |
                          ./harness_scripts/base_check/integration_tests_entrypoint.sh
                      description: This test requires java and maven to be installed
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
  identifier: base_checks
  name: base_checks
  description: Run unit and integration tests on every PR
