pipeline:
  name: publish to docker
  identifier: publish_to_docker
  projectIdentifier: datarobotusermodels
  orgIdentifier: Custom_Models
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: datarobot-user-models
        build: <+input>
  stages:
    - stage:
        name: build_and_publish
        identifier: build_and_publish
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Get Environment Version
                  identifier: Get_Environment_Version
                  spec:
                    shell: Sh
                    command: |-
                      cd $ENV_DIR
                      export ENV_VERSION_ID=$(jq -r '.environmentVersionId' env_info.json)
                    envVariables:
                      ENV_DIR: <+pipeline.variables.env_folder>/<+pipeline.variables.env_name>
                    outputVariables:
                      - name: ENV_VERSION_ID
                        type: String
                        value: ENV_VERSION_ID
                  description: Extract the environment version ID from env_info.json
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: datarobot_user_models_read_write
                    repo: datarobotdev/env-<+pipeline.variables.repo_name>
                    tags:
                      - v10.2-<+execution.steps.Get_Environment_Version.output.outputVariables.ENV_VERSION_ID>
                      - latest
                    caching: true
                    dockerfile: <+pipeline.variables.env_folder>/<+pipeline.variables.env_name>/Dockerfile
                    context: <+pipeline.variables.env_folder>/<+pipeline.variables.env_name>
  variables:
    - name: env_folder
      type: String
      description: ""
      required: true
      value: <+input>.allowedValues(public_dropin_environments, public_dropin_gpu_environments, public_dropin_environments_sandbox)
    - name: env_name
      type: String
      description: ""
      required: true
      value: <+input>
    - name: release_version
      type: String
      description: ""
      required: true
      value: <+input>
    - name: repo_name
      type: String
      description: ""
      required: true
      value: <+input>
