trigger:
  name: python3_pmml local on pr
  identifier: python3_pmml_local_on_pr
  enabled: true
  stagesToExecute: []
  description: ""
  tags: {}
  encryptedWebhookSecretIdentifier: ""
  orgIdentifier: Custom_Models
  projectIdentifier: datarobotusermodels
  pipelineIdentifier: test_functional_by_framework
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: account.svc_harness_git1
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: master
          headerConditions: []
          repoName: datarobot-user-models
          actions:
            - Open
            - Reopen
            - Synchronize
  pipelineBranchName: <+trigger.branch>
  inputSetRefs:
    - python3_pmml_local_default_pr_input
