pipeline:
  projectIdentifier: datarobotusermodels
  orgIdentifier: Custom_Models
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: datarobot-user-models
        build: <+input>
  stages:
    - parallel:
        - stage:
            name: test mlops reporting
            identifier: mlops_reporting
            description: This was historically separated from all the oter functional tests as MLOps package should be installed
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: test mlops reporting
                      identifier: Run_1
                      spec:
                        shell: Bash
                        command: |-
                          ./harness_scripts/functional_general/mlops_reporting_entrypoint.sh \
                            <+secrets.getValue("org.genai-systems-dockerhub-login")> <+secrets.getValue("org.genai-systems-dockerhub-token")>
                        resources:
                          limits:
                            memory: 3G
                      description: |-
                        This test checks mlops reporting.

                        It is implemented as a separate stage because we need to install mlops and tracking agent jar.

                        I think this could be merged with "test functional general"
              caching:
                enabled: false
                paths: []
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
            timeout: 15m
        - stage:
            name: test inference custom java predictor
            identifier: custom_java_predictor
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: test inference custom java predictor
                      identifier: test_inference_custom_java_predictor
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: datarobot/drum-builder:ubuntu-22-04
                        shell: Bash
                        command: ./harness_scripts/functional_general/custom_java_predictor_entrypoint.sh
                        resources:
                          limits:
                            memory: 3G
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
            timeout: 15m
        - stage:
            name: test functional general
            identifier: general_tests
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Run
                      name: test functional general
                      identifier: test_functional_general
                      spec:
                        connectorRef: account.dockerhub_datarobot_read
                        image: python:3.11-bookworm
                        shell: Bash
                        command: |
                          apt update; apt install -y docker.io python3-docker python3-venv r-base
                          python3 -m venv /opt/venv
                          source /opt/venv/bin/activate
                          #python3 -m pip install -r custom_model_runner/requirements.txt
                          touch /opt/input.csv
                          # Required otherwise it looks at /opt/model which doesn't exist
                          cp -r custom_model_runner /opt/model

                          ./harness_scripts/functional_general/general_tests_entrypoint.sh \
                            <+secrets.getValue("org.genai-systems-dockerhub-login")> <+secrets.getValue("org.genai-systems-dockerhub-token")>
                        resources:
                          limits:
                            memory: 8G
              caching:
                enabled: false
                paths: []
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
            timeout: 60m
  identifier: test_functional_general
  name: test functional general
  allowStageExecutions: true
  description: Runs functional tests on every PR
