pipeline:
  projectIdentifier: datarobotusermodels
  orgIdentifier: Custom_Models
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svc_harness_git1
        repoName: datarobot-user-models
        build: <+input>
  stages:
    - stage:
        name: Check if framework env has changed
        identifier: check_env_changed
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: build_list_of_environments_to_test_on
                  identifier: build_list_of_environments_to_test_on
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    shell: Sh
                    command: |-
                      matrix_values=$(python3 ./harness_scripts/functional_by_framework_multistep/generate_testlist.py ./tests/functional/test_per_framework.json ./)
                      echo ${matrix_values}
                    outputVariables:
                      - name: matrix_values
          caching:
            enabled: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Test functional by framework
        identifier: check_by_framework
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run functional test in provided framework
                  identifier: Run_1
                  strategy:
                    matrix:
                      env: <+json.list("environments", <+pipeline.stages.check_env_changed.spec.execution.steps.check_diff.output.outputVariables.matrix_values>)>
                      nodeName: <+matrix.env.env_folder>/<+matrix.env.framework> - <+matrix.env.tag>
                  spec:
                    connectorRef: datarobot_user_models_read_write
                    image: datarobotdev/<+matrix.env.repo>:<+matrix.env.tag>
                    shell: Sh
                    command: |-
                      echo "Checking if test for local should run"
                      echo "Tag: <+matrix.image_tag>"
                      echo "Dockerfile.local exists: <+pipeline.stages.check_env_changed.spec.execution.steps.check_diff.output.outputVariables.dockerfile_local_exists>"

                      if [[ "<+matrix.image_tag>" == *local* && <+pipeline.stages.check_env_changed.spec.execution.steps.check_diff.output.outputVariables.dockerfile_local_exists> == false ]]; then
                        echo "Dockerfile.local does not exist, skippinig test"
                        exit 0
                      fi
                      ./harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh \
                        <+matrix.env.framework> <+matrix.env.env_folder>
                    resources:
                      limits:
                        memory: 3G
                  when:
                    stageStatus: Success
          caching:
            enabled: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        when:
          pipelineStatus: Success
        strategy:
          matrix:
            abc:
              - a
              - b
  identifier: Test_functional_by_framework_multisteps
  description: |-
    Runs functional tests for each framework in a corresponding image.
    If only DRUM changed in the PR, latest image is taken for every framework, DRUM installed and tests run.
    If environment itself has changed, temporary image is built.
  name: Test functional by framework - multisteps
