from datarobot_drum.custom_task_interfaces.transform_interface import TransformerInterface

from datarobot_drum.custom_task_interfaces.estimator_interface import EstimatorInterface
from datarobot_drum.custom_task_interfaces.binary_classification import (
    BinaryClassificationInterface,
)
from datarobot_drum.custom_task_interfaces.regression_interface import RegressionInterface
from datarobot_drum.custom_task_interfaces.multiclass_classification import MultiClassificationInterface
from datarobot_drum.custom_task_interfaces.anomaly_interface import AnomalyInterface
