# Constants to access pipeline json fields
PIPELINE_NAME_FIELD = "name"
PIPELINE_ENGINE_TYPE_FIELD = "engineType"
PIPELINE_LANGUAGE_FIELD = "language"
PIPELINE_SYSTEM_CONFIG_FIELD = "systemConfig"
PIPELINE_EE_CONF_FIELD = "executionEnvironment"
PIPELINE_PIPE_FIELD = "pipe"
PIPELINE_COMP_ID_FIELD = "id"
PIPELINE_COMP_TYPE_FIELD = "type"
PIPELINE_COMP_ARGUMENTS_FIELD = "arguments"
PIPELINE_COMP_PARENTS_FIELD = "parents"
PIPELINE_COMP_PARENTS_FIRST_FIELD = "parent"
PIPELINE_COMP_PARENTS_SECOND_FIELD = "output"
PIPELINE_COMP_PARENTS_THIRD_FIELD = "input"

# Constants to access component description json fields
COMPONENT_DESC_ENGINE_TYPE_FIELD = "engineType"
COMPONENT_DESC_NAME_FIELD = "name"
COMPONENT_DESC_VERSION_FIELD = "version"
COMPONENT_DESC_LABEL_FIELD = "label"
COMPONENT_DESC_PROGRAM_FIELD = "program"
COMPONENT_DESC_LANGUAGE_FIELD = "language"
COMPONENT_DESC_DESCRIPTION_FIELD = "description"
COMPONENT_DESC_CLASS_FIELD = "componentClass"
COMPONENT_DESC_MODEL_BEHAVIOR_FIELD = "modelBehavior"
COMPONENT_DESC_USE_MLOPS_FIELD = "useMLOps"
COMPONENT_DESC_GROUP_FIELD = "group"
COMPONENT_DESC_INPUT_INFO_FIELD = "inputInfo"
COMPONENT_DESC_OUTPUT_INFO_FIELD = "outputInfo"
COMPONENT_DESC_ARGUMENTS = "arguments"
COMPONENT_DESC_USER_STAND_ALONE = "userStandalone"
COMPONENT_DESC_PYTHON_DEPS = "deps"
COMPONENT_DESC_INCLUDE_GLOB_PATTERNS = "includeGlobPatterns"
COMPONENT_DESC_EXCLUDE_GLOB_PATTERNS = "excludeGlobPatterns"


COMPONENT_DESC_ARGUMENT_KEY = "key"
COMPONENT_DESC_ARGUMENT_TYPE = "type"
COMPONENT_DESC_ARGUMENT_LABEL = "label"
COMPONENT_DESC_ARGUMENT_DESCRIPTION = "description"
COMPONENT_DESC_ARGUMENT_ENV_VAR = "envVar"
COMPONENT_DESC_ARGUMENT_OPTIONAL = "optional"
COMPONENT_DESC_ARGUMENT_TAG = "tag"
COMPONENT_DESC_ARGUMENT_DEFAULT_VAL = "defaultValue"


CONNECTION_DESC_DESCRIPTION_FIELD = "description"
CONNECTION_DESC_LABEL_FIELD = "label"
CONNECTION_DESC_DEFAULT_COMPONENT_FIELD = "defaultComponent"
CONNECTION_DESC_TYPE_FIELD = "type"
CONNECTION_DESC_GROUP_FIELD = "group"

# Auto-generated internal fields
COMPONENT_DESC_ROOT_PATH_FIELD = "root-path"

# Component metadata reference json
COMPONENT_METADATA_REF_FILE_NAME_FIELD = "metadataFilename"


PIPELINE_SYSTEM_CONFIG_TEST_MODE_PARAM = "__test_mode__"
