pipeline:
  name: Bump Env Info
  identifier: Bump_Env_Info
  projectIdentifier: datarobotusermodels
  orgIdentifier: Custom_Models
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.svcharnessgit1sshhhi
        repoName: datarobot-user-models
        build: <+input>
        sparseCheckout: []
        depth: 0
  stages:
    - stage:
        name: Bump and PR
        identifier: Bump_and_PR
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.dockerhub_datarobot_read
                    image: datarobotdev/genai-ci-tools:latest
                    shell: Bash
                    command: |-
                      git config --global user.email "genai-systems-devs@datarobot.com" 
                      git config --global user.name "GenAI Git Bot"

                      mkdir -p ~/.ssh
                      ssh-keyscan github.com >> ~/.ssh/known_hosts
                      printf '%s\n' "<+secrets.getValue("account.svc-harness-git1-id_ed25519")>" >> ~/.ssh/id_ed25519
                      chmod 600 ~/.ssh/id_ed25519

                      export GH_TOKEN="<+secrets.getValue("account.githubpatsvcharnessgit2")>"
                      git fetch origin
                      .harness/scripts/env_info_bump.sh
