/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2020-07-17T16:40:34.780-04:00
  3.30.0.6
  
  Standalone prediction code with sample test data for XGBoostModel named XGBoost_grid__1_AutoML_20200717_163214_model_159

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://192.168.86.240:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://192.168.86.240:54321/3/Models.java/XGBoost_grid__1_AutoML_20200717_163214_model_159 > XGBoost_grid__1_AutoML_20200717_163214_model_159.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m XGBoost_grid__1_AutoML_20200717_163214_model_159.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="XGBoost_grid__1_AutoML_20200717_163214_model_159", algorithm="xgboost")
public class XGBoost_grid__1_AutoML_20200717_163214_model_159 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Binomial; }

  public boolean isSupervised() { return true; }
  public int nclasses() { return 2; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_XGBoost_grid__1_AutoML_20200717_163214_model_159.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 2;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* SepalLengthCm */ null,
    /* SepalWidthCm */ null,
    /* PetalLengthCm */ null,
    /* PetalWidthCm */ null,
    /* Species */ XGBoost_grid__1_AutoML_20200717_163214_model_159_ColInfo_4.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.6697247706422018,0.3302752293577982};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = null;

  public XGBoost_grid__1_AutoML_20200717_163214_model_159() { super(NAMES,DOMAINS,"Species"); }
  public String getUUID() { return Long.toString(-5788257416375362180L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    float preds_0 = 0f;
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_0.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_1.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_2.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_3.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_4.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_5.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_6.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_7.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_8.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_9.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_10.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_11.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_12.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_13.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_14.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_15.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_16.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_17.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_18.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_19.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_20.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_21.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_22.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_23.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_24.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_25.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_26.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_27.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_28.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_29.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_30.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_31.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_32.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_33.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_34.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_35.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_36.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_37.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_38.score0(data);
    preds_0 += XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_39.score0(data);
    preds_0 += -0.0f;
    preds[0] = preds_0;
    preds[0] = (float) 1./(1. + Math.min(1e19, Math.exp(-(preds[0]))));
    preds[1] = 1f - preds[0];
    preds[2] = preds[0];
    preds[0] = GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.9553513526916504);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_XGBoost_grid__1_AutoML_20200717_163214_model_159 implements java.io.Serializable {
  public static final String[] VALUES = new String[4];
  static {
    NamesHolder_XGBoost_grid__1_AutoML_20200717_163214_model_159_0.fill(VALUES);
  }
  static final class NamesHolder_XGBoost_grid__1_AutoML_20200717_163214_model_159_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "SepalLengthCm";
      sa[1] = "SepalWidthCm";
      sa[2] = "PetalLengthCm";
      sa[3] = "PetalWidthCm";
    }
  }
}
// The class representing column Species
class XGBoost_grid__1_AutoML_20200717_163214_model_159_ColInfo_4 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    XGBoost_grid__1_AutoML_20200717_163214_model_159_ColInfo_4_0.fill(VALUES);
  }
  static final class XGBoost_grid__1_AutoML_20200717_163214_model_159_ColInfo_4_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "Iris-setosa";
      sa[1] = "Iris-versicolor";
    }
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_0 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.6f) ?
      -0.59738374f
      :
      0.5953608f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_1 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.75f) ?
      ((Double.isNaN(data[2]) || ((float)data[2]) < 2.6f) ?
        -0.46242172f
        :
        0.4466034f
      )
      :
      0.45822087f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_2 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.7f) ?
      -0.40810442f
      :
      0.39827448f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_3 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.6f) ?
      -0.36802554f
      :
      0.36338058f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_4 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 0.75f) ?
      -0.34727794f
      :
      0.33943397f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_5 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.6f) ?
      -0.32727543f
      :
      0.3226024f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_6 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 0.75f) ?
      -0.31787196f
      :
      0.3093488f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_7 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.6f) ?
      -0.30774808f
      :
      0.29845247f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_8 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[2]) || ((float)data[2]) < 2.6f) ?
      -0.29911032f
      :
      0.28844678f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_9 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[0]) || ((float)data[0]) < 5.55f) ?
      -0.25951004f
      :
      0.17191266f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_10 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 0.25f) ?
      -0.2752676f
      :
      0.063544184f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_11 {
  static float score0(double[] data) {
    return     -0.04924437f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_12 {
  static float score0(double[] data) {
    return     -0.060959455f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_13 {
  static float score0(double[] data) {
    return     ((Double.isNaN(data[3]) || ((float)data[3]) < 0.35000002f) ?
      -0.27509117f
      :
      0.15738794f
    );
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_14 {
  static float score0(double[] data) {
    return     -0.02633306f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_15 {
  static float score0(double[] data) {
    return     -0.020032208f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_16 {
  static float score0(double[] data) {
    return     -0.018995322f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_17 {
  static float score0(double[] data) {
    return     -0.007042021f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_18 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_19 {
  static float score0(double[] data) {
    return     -0.006514132f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_20 {
  static float score0(double[] data) {
    return     -0.0068162964f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_21 {
  static float score0(double[] data) {
    return     -0.0010681571f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_22 {
  static float score0(double[] data) {
    return     -8.9461927E-4f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_23 {
  static float score0(double[] data) {
    return     -0.024640651f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_24 {
  static float score0(double[] data) {
    return     -0.0064006634f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_25 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_26 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_27 {
  static float score0(double[] data) {
    return     -7.909516E-4f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_28 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_29 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_30 {
  static float score0(double[] data) {
    return     -0.010487579f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_31 {
  static float score0(double[] data) {
    return     -0.0015372428f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_32 {
  static float score0(double[] data) {
    return     0.0063151764f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_33 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_34 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_35 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_36 {
  static float score0(double[] data) {
    return     -0.004535194f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_37 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_38 {
  static float score0(double[] data) {
    return     -0.02009372f;
  }
}

class XGBoost_grid__1_AutoML_20200717_163214_model_159_Tree_g_0_t_39 {
  static float score0(double[] data) {
    return     -0.0f;
  }
}

