# This is the default base image for use with user models and workflows.
# It contains a variety of common useful data-science packages and tools.
FROM apline


ENTRYPOINT ["/opt/code/start_server.sh"]
