pipeline:
  name: fips-python3-keras_public-dropin-environments
  identifier: fipspython3keras_publicdropinenvironments
  projectIdentifier: datarobotusermodels
  orgIdentifier: Custom_Models
  tags: {}
  template:
    templateRef: reconcile_dependencies_template
    versionLabel: 0.0.0
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
      variables:
        - name: env_dir
          type: String
          value: public_dropin_environments_sandbox/fips_python3_keras
        - name: image_uri
          type: String
          value: datarobotdev/mirror_chainguard_datarobot.com_python-fips:3.11-dev
