JSON_INFO_ENV = "MCENTER_MODEL_CONNECTOR_JSON_INFO"
TMP_DIR_ENV = "MCENTER_MODEL_CONNECTOR_TMP_DIR"

MODEL_CONNECTOR_CMD_OPTION = "cmd"
MODEL_CONNECTOR_IMPORT_CMD = "import"
MODEL_CONNECTOR_LIST_PARAM_CMD = "list-params"
