# Copyright 2021 DataRobot, Inc. and its affiliates.
#
# All rights reserved.
#
# 
#
# This is proprietary source code of DataRobot, Inc. and its affiliates.
#
# Released under the terms of DataRobot Tool and Utility Agreement.
init <- function(...) {
    library(brnn)
    library(glmnet)
}

transform <- function(data, model) {
    data[is.na(data)] <- 0
    data
}


# NOTE: In this model template DRUM is automatically loading "r_reg.rds"
#
# Some hooks are omitted here as they are implicitly generated by the DRUM library.
# This happens because DRUM knows how to work with many known types of models.
# They can be overriden in order to change the default behavior:
#
# load_model <- function(input_dir) {
#     ...
# }
#
# score <- function(data, model, ...) {
#     ...
# }
#
# See more about the built-in support of models:
# https://github.com/datarobot/datarobot-user-models/blob/master/DEFINE-INFERENCE-MODEL.md#built-in-model-support